### ISSUE TITLE
Modify iFrame to include all cohort Staff Notes links

### ISSUE THREAD

**Issue by magee** [ph8tel/RPT-Chrome-Extension#1]
https://puu.sh/AAcvA/25162869d1.png

Perhaps add something like this with each cohort id linked to their staff notes form:
Staff Notes:  RPT05  RPT06  RPT07  RPT08

**Comment by ph8tel** [comment]
Staff links moved into css controlled display by button toggle by this commit: 
**https://github.com/ph8tel/RPT-Chrome-Extension/commit/d6b224b167daca3455b86ee3b9b757eb495c68c0**

**Comment by magee** [comment]
Can we re-open this?   I think you may have missed the intention of this issue.  We need to have links to several Staff Notes forms rather than one.  One way we might be able to manage that while keeping the simplicity of the interface is to do something like this with each cohort id being a link to their Staff Notes form.  

```
Staff Notes: RPT05 RPT06 RPT07 RPT08
```

Also, I do have a spreadsheet where I keep cohort data like that which could be used programmatically.  I may break it out into an independent resource to be more broadly available.  Will let you know.
