### ISSUE TITLE
Move Staff Notes links to above iFrame

### ISSUE THREAD

**Issue by magee** [ph8tel/RPT-Chrome-Extension#2]
Users have to scroll to bottom of the screen to see that the links are there.  That relies on them remembering it's there.  

Extra goodness...  It will be an even more useful tool if folks can use it just to get to the Staff Notes visible right at the top.

**Comment by ph8tel** [comment]
```             showStaffNotes = () => {
                let staffNotes = document.getElementById("staff-notes")
                staffNotes.style.display === "none" ?
                    staffNotes.style.display = "block" :
                    staffNotes.style.display = "none"
            }
```
Great idea! Extra goodness in place with commit:
https://github.com/ph8tel/RPT-Chrome-Extension/commit/d6b224b167daca3455b86ee3b9b757eb495c68c0
