### ISSUE TITLE
Change Form title from 'Pairing' to 'Student' for broader use. 

### ISSUE THREAD

**Issue by magee** [ph8tel/RPT-Chrome-Extension#6]
"Pairing Observations" to "Student Observations"

**Comment by ph8tel** [comment]
Title updated in issue resolved with this commit:
https://github.com/ph8tel/RPT-Chrome-Extension/commit/6af14c8ebcddd5d203caf8a32ee1e5d8fcf6821c

**Comment by magee** [comment]
Thanks for making that change.  I was actually referring to the title in the form file itself that still says "Pair Observation."  I notice also that the label "HiR Name" should also be changed just to "Name"
